resolver: lts-7.15

flags: {}

packages:
- '.'
- location: ../nanovg-hs
  extra-dep: true
- location:
    git: https://github.com/vagarenko/reactive-banana-glfw.git
    commit: 9a7ced089bca2e2b9f1a74f4c10d54a037f01957
  extra-dep: true

extra-deps:
- pqueue-1.3.2
- reactive-banana-1.1.0.1

extra-package-dbs: []